Repository ucsb-cs156-f23/proj-happycows-f23-5pm-3, pull requests merged in 2023-11, with the labels that each got.

#26 ky - updated chat feature with new ui designs
  frontend/src/assets/ChatBubble.svg
  frontend/src/assets/ChatClosedIcon.svg
  frontend/src/assets/ChatOpenedIcon.svg
  frontend/src/main/components/Chat/ChatFeature.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: 10

#23 #10 Changed commons default values to be settable by .env variables a…
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
Labels: 10

#22 FEATURE: Eliminate purchase notification popups
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: 5, Merge Candidate

#27 KT - FEATURE: Fix UI/UX on Admin Commons List page
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
Labels: 5, Merge Candidate

#28 Added entity and repository for Announcement
  src/main/java/edu/ucsb/cs156/happiercows/entities/Announcement.java
  src/main/java/edu/ucsb/cs156/happiercows/repositories/AnnouncementRepository.java
Labels: 10, Merge Candidate

#32 Karim: Farmer Greetings UI Improvement
  frontend/src/main/components/Commons/CommonsPlay.js
  frontend/src/main/pages/HomePage.css
  frontend/src/main/pages/HomePage.js
  frontend/src/tests/components/Commons/CommonsPlay.test.js
  frontend/src/tests/pages/HomePage.test.js
Labels: 10

#21 Made Instructor Report Improvements
  frontend/src/main/components/Reports/ReportHeaderTable.js
  frontend/src/main/components/Reports/ReportLineTable.js
  frontend/src/main/components/Reports/ReportTable.js
  frontend/src/tests/components/Reports/ReportHeaderTable.test.js
  frontend/src/tests/components/Reports/ReportLineTable.test.js
  frontend/src/tests/components/Reports/ReportTable.test.js
Labels: FIXME - Need peer CR

#20 FEATURE: UX improvements to leaderboard page
  frontend/src/main/components/Leaderboard/LeaderboardTable.js
  frontend/src/main/pages/LeaderboardPage.js
  frontend/src/tests/components/Leaderboard/LeaderboardTable.test.js
  frontend/src/tests/pages/LeaderboardPage.test.js
Labels: 10, Merge Candidate

#19 Added Lastday
  frontend/src/fixtures/commonsFixtures.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/AdminCreateCommonsPage.js
  frontend/src/main/pages/AdminEditCommonsPage.js
  frontend/src/tests/components/Commons/CommonsForm.test.js
  frontend/src/tests/pages/AdminCreateCommonsPage.test.js
  frontend/src/tests/pages/AdminEditCommonsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
  src/main/java/edu/ucsb/cs156/happiercows/entities/Commons.java
  src/main/java/edu/ucsb/cs156/happiercows/models/CreateCommonsParams.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/CommonsControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/entities/CommonsTest.java
Labels: 10, Merge Candidate

#33 Oj - Added default ui for commons
  frontend/src/main/components/Commons/CommonsList.js
  frontend/src/tests/components/Commons/CommonsList.test.js
Labels: 5, Merge Candidate
